### ISSUE TITLE
WIGGLES SUCKS

### ISSUE THREAD

**Issue by TheRealZenald** [TheActualZenald/gamedev#2]
JIMMY NEWTRON LOOKING BOY

**Comment by J-0-E** [comment]
`

**Comment by TheActualZenald** [comment]
shut up bald lookin tate lovin burger king looking headass

**Comment by J-0-E** [comment]
yea Daniel

**Comment by TheRealZenald** [comment]
Shut the freak up you starved jimmy neutron

**Comment by TheActualZenald** [comment]
you cost 8 elixr shut up
